name: Discord Notification

on: [push, pull_request]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Notification
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: A new commit has been pushed to the repository
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
